### PR TITLE
fill in edges and delete edge masks 

### PR DESCRIPTION
**Pull request by brandenkmurray**
I've filled in the edges for all of the images mentioned in #6 except for `a1777737270c5f96c4523dff76e4097756f8f7d4c9d59bac079e31f9510deabd` which is split into two masks in #2.

### CODE REVIEW

**Comment by lopuhin** [comment]
Looks good except for https://github.com/lopuhin/kaggle-dsbowl-2018-dataset-fixes/pull/7/files#diff-aa296e86a310d7c551fd1d6fa35c4e4b - is it correct that it is removed? Does not look like an edge mask to me.

**Comment by brandenkmurray** [comment]
Added old mask back and removed the correct one

**Comment by lopuhin** [comment]
Looks good, thanks @brandenkmurray ! Let me resolve the conflict I introduced by merging a part of #2

**Comment by lopuhin** [comment]
Merged, the changes: https://github.com/lopuhin/kaggle-dsbowl-2018-dataset-fixes/compare/617386364d7dec8ebefffbab43d820737d628320...60832d720574a8450e136cad977e04a4a7182c3c

**Pull request merged**
